{
 "title": "Smoke Ping",
 "description": "Smoke Ping using https://github.com/SuperQ/smokeping_prober\r\nwith \r\nlatency heatmap\r\nlatency graph\r\npacket loss gragh\r\n",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "label_values(smokeping_response_duration_seconds_bucket, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Smoke Ping - $target",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(smokeping_response_duration_seconds_bucket{host=\"$target\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Packet Loss - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(smokeping_requests_total{host=\"$target\"} - smokeping_response_duration_seconds_count{host=\"$target\"})/smokeping_requests_total{host=\"$target\"} ",
     "legendFormat": "Percentage"
    },
    {
     "expr": "(smokeping_requests_total{host=\"$target\"} - smokeping_response_duration_seconds_count{host=\"$target\"})",
     "legendFormat": "Count"
    },
    {
     "expr": "(rate(smokeping_requests_total{host=\"$target\"}[$__interval]) - rate(smokeping_response_duration_seconds_count{host=\"$target\"}[$__interval]))/rate(smokeping_requests_total{host=\"$target\"}[$__interval])",
     "legendFormat": "irate"
    }
   ]
  },
  {
   "title": "Latency - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(smokeping_response_duration_seconds_sum{host=\"$target\"}[$__interval]) / irate(smokeping_response_duration_seconds_count{host=\"$target\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}